# Generated by Django 4.0.5 on 2022-10-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaComInformacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(default=0)),
                ('curso', models.CharField(max_length=200)),
                ('aniversario', models.CharField(max_length=10)),
                ('periodo', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
                ('ponto_de_encontro', models.CharField(max_length=200)),
            ],
        ),
    ]
