# Generated by Django 4.0.5 on 2022-11-26 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='images/imagem_em_branco.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='aniversario',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='aniversario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='images/perfil_vazio.jpeg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='webmail',
            field=models.EmailField(max_length=200, unique=True, verbose_name='webmail'),
        ),
    ]
