# Generated by Django 4.0.5 on 2022-10-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0003_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='aniversario',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='periodo',
            field=models.IntegerField(default=1),
        ),
    ]
