# Generated by Django 4.0.5 on 2022-11-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0003_alter_evento_foto_alter_usuario_aniversario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='criador',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='images/perfil_vazio.jpeg', upload_to='images'),
        ),
    ]
