# Generated by Django 4.0.5 on 2022-10-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0004_usuario_nome_alter_usuario_aniversario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='aniversario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ponto_de_encontro',
            field=models.CharField(default='', max_length=200),
        ),
    ]
