# Generated by Django 4.0.5 on 2022-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0004_evento_criador_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(default='images/padrao_evento.png', upload_to='images'),
        ),
    ]
