# Generated by Django 4.0.5 on 2022-10-14 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0006_delete_caixacominformacoes_delete_carona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aniversario',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='periodo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ponto_de_encontro',
            field=models.CharField(max_length=200),
        ),
    ]
