# Generated by Django 4.0.5 on 2022-10-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PUCBook_Site', '0007_usuario_aniversario_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseCarona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesse1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesse2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='interesse3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='periodo',
            field=models.IntegerField(default=0),
        ),
    ]
